#ifndef ENCRYPT_H
#define ENCRYPT_H

/**
 * @brief Reports the error generated by the OpenSSL library
 *
 */
void handleErrors(void);

/**
 * @brief  Encrypts the data using the key and iv provided
 *
 * @param plaintext Text to be encrypted
 * @param plaintext_len  Length of the text to be encrypted
 * @param key Key to be used for encryption
 * @param iv Initialization vector
 * @param ciphertext Ciphertext generated after encryption
 */
void encryptData(const unsigned char *plaintext, int plaintext_len,
                 unsigned char *key, unsigned char *iv,
                 unsigned char *ciphertext);

#endif